name: Deploy to Production
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 64.225.9.200
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/www/training.train5d.com
            # Set the correct SSH key for Git to use when connecting to GitHub
            git config --local core.sshCommand "ssh -i ~/.ssh/github_push"
            git pull origin main
