name: Manual Deploy to Production

on:
  workflow_dispatch:  # Only runs when manually triggered

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
        
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@64.225.9.200 "cd /var/www/training.train5d.com && git pull origin main && exit"
